### ISSUE TITLE
Regarding tutorial-3 Supervised Learning

### ISSUE THREAD

**Issue by vibhapatelddu** [Eldave93/Seizure-Detection-Tutorials#1]
Hi, Thank you for posting the tutorials. I need some help in tutorial 3- Supervised Learning. With the help of tutorial-2 I have created features for CHB-MIT dataset. Now, stuck in following:
1. Dont know how to create feature's .json file. It is mentioned that  notebook "Extra 01. Assemble Feature DataFrames" can be used for it, but could not find it.
2. How to bifurcate features of seizure and nonseizure events for CHB-MIT dataset, as seizure-start time and seizure-end time is mentioned in summary file. (As all files are different in Epileptologie dataset)

Once again thank you for tutorials, and a little hint on above would help a lot.

**Comment by Eldave93** [comment]
Sorry for the delay in getting back to you.

Regarding question 1 I will be releasing that code later in the year once I have submitted my PhD. As it's tied to some of the work in there I should be releasing that stuff around then.

For question 2, getting the seizure times for the CHB-MIT dataset was a bit more work as you could imagine. What I did was create a function using regular expressions to parse the summary.txt files so I had the start and end times for the seizures. I then created a long Series of 0's (representing interictal periods) the length of the data and added in 1's where seizures were - paying attention to the sampling rate. That's also in the extra notebook too when I release it :)

**Comment by vibhapatelddu** [comment]
Thank you for the response, and best wishes for PhD! :)
